### ISSUE TITLE
Logical fields not working correctly

### ISSUE THREAD

**Issue by rnixdorf** [episage/dbf-parser#8]
In recordFunctions.js line 38 the switch is testing value against the cases which will either be true or false so the default is always reached.  The switch needs to be 'switch (true)'

**Comment by episage** [comment]
I probably fixed it in `2.1.1`. Does it work for you?

**Comment by rnixdorf** [comment]
Yes it works.  Thanks

**Comment by rnixdorf** [comment]
I don't see date as a parsed field type.  Do I have to determine myself if it is a date?

**Comment by episage** [comment]
It's best for you to parse it yourself because `new Date()` does not handle timezones very well. I released `3.0.0` that returns
```
{
    field,
    buffer,
    encoding,
    stringValue: value,
}
```
in case field has not been parsed. You can inspect `field.type` and parse according to https://www.dbase.com/Knowledgebase/INT/db7_file_fmt.htm#:~:text=8%20bytes%20%2D%20date%20stored%20as%20a%20string%20in%20the%20format%20YYYYMMDD.

Here's a snippet:
```
    let year = parseInt(value.substring(0, 4));
    let month = parseInt(value.substring(4, 6));
    let day = parseInt(value.substring(6, 8));
    new Date(year, month - 1, day);
```

**Comment by rnixdorf** [comment]
Date field is returning as type 'C'.  Should it return as type 'D'?

Nevermind, it is a type 'C' in dbase.

**Comment by rnixdorf** [comment]
Thank you for the changes
